# Generated by Django 3.2.18 on 2023-07-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('userid', models.CharField(db_column='userId', max_length=20, primary_key=True, serialize=False)),
                ('userpw', models.CharField(db_column='userPw', max_length=20)),
                ('username', models.CharField(db_column='userName', max_length=10)),
                ('useremail', models.CharField(db_column='userEmail', max_length=40)),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookmarkva',
            fields=[
                ('bookmarkvaid', models.IntegerField(db_column='bookmarkvaId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bookmarkva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookmarkwp',
            fields=[
                ('bookmarkwpid', models.IntegerField(db_column='bookmarkwpId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bookmarkwp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conv',
            fields=[
                ('convid', models.CharField(db_column='convId', max_length=30, primary_key=True, serialize=False)),
                ('convpoiname', models.CharField(db_column='convPoiName', max_length=30)),
                ('convclname', models.CharField(blank=True, db_column='convClName', max_length=10, null=True)),
                ('convctprvnname', models.CharField(blank=True, db_column='convCtprvnName', max_length=10, null=True)),
                ('convsignguname', models.CharField(blank=True, db_column='convSignguName', max_length=10, null=True)),
                ('convlegaldongcd', models.CharField(blank=True, db_column='convLegaldongCd', max_length=10, null=True)),
                ('convlegaldongname', models.CharField(blank=True, db_column='convLegaldongName', max_length=10, null=True)),
                ('convla', models.FloatField(db_column='convLa')),
                ('convlo', models.FloatField(db_column='convLo')),
                ('convclnamectg', models.CharField(blank=True, db_column='convClNameCtg', max_length=10, null=True)),
            ],
            options={
                'db_table': 'conv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medi',
            fields=[
                ('mediid', models.CharField(db_column='mediId', max_length=30, primary_key=True, serialize=False)),
                ('medipoiname', models.CharField(db_column='mediPoiName', max_length=30)),
                ('mediclname', models.CharField(blank=True, db_column='mediClName', max_length=10, null=True)),
                ('medictprvnname', models.CharField(blank=True, db_column='mediCtprvnName', max_length=10, null=True)),
                ('medisignguname', models.CharField(blank=True, db_column='mediSignguName', max_length=10, null=True)),
                ('medilegaldongcd', models.CharField(blank=True, db_column='mediLegaldongCd', max_length=10, null=True)),
                ('medilegaldongname', models.CharField(blank=True, db_column='mediLegaldongName', max_length=10, null=True)),
                ('medila', models.FloatField(db_column='mediLa')),
                ('medilo', models.FloatField(db_column='mediLo')),
                ('mediclnamectg', models.CharField(blank=True, db_column='mediClNameCtg', max_length=10, null=True)),
            ],
            options={
                'db_table': 'medi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('parkingid', models.CharField(db_column='parkingId', max_length=30, primary_key=True, serialize=False)),
                ('parkingfcltyname', models.CharField(db_column='parkingFcltyName', max_length=30)),
                ('parkingctprvnname', models.CharField(blank=True, db_column='parkingCtprvnName', max_length=10, null=True)),
                ('parkingsignguname', models.CharField(blank=True, db_column='parkingSignguName', max_length=10, null=True)),
                ('parkinglegaldongcd', models.CharField(blank=True, db_column='parkingLegaldongCd', max_length=10, null=True)),
                ('parkinglegaldongname', models.CharField(blank=True, db_column='parkingLegaldongName', max_length=10, null=True)),
                ('parkingaddrnew', models.CharField(blank=True, db_column='parkingAddrNew', max_length=50, null=True)),
                ('parkingla', models.FloatField(db_column='parkingLa')),
                ('parkinglo', models.FloatField(db_column='parkingLo')),
                ('parkingflagname', models.CharField(blank=True, db_column='parkingFlagName', max_length=10, null=True)),
                ('parkingparkingspceco', models.IntegerField(blank=True, db_column='parkingParkingSpceCo', null=True)),
                ('parkingutiliizalmttflagname', models.CharField(blank=True, db_column='parkingUtiliizaLmttFlagName', max_length=10, null=True)),
                ('parkingwkdayname', models.CharField(blank=True, db_column='parkingWkdayName', max_length=20, null=True)),
                ('parkingworkdayopenbsnstime', models.CharField(blank=True, db_column='parkingWorkdayOpenBsnsTime', max_length=10, null=True)),
                ('parkingworkdayclostime', models.CharField(blank=True, db_column='parkingWorkdayClosTime', max_length=10, null=True)),
                ('parkingsatopenbsnstime', models.CharField(blank=True, db_column='parkingSatOpenBsnsTime', max_length=10, null=True)),
                ('parkingsatclostime', models.CharField(blank=True, db_column='parkingSatClosTime', max_length=10, null=True)),
                ('parkingsunopenbsnstime', models.CharField(blank=True, db_column='parkingSunOpenBsnsTime', max_length=10, null=True)),
                ('parkingsunclostime', models.CharField(blank=True, db_column='parkingSunClosTime', max_length=10, null=True)),
                ('parkingutiliizachrgecn', models.CharField(blank=True, db_column='parkingUtiliizaChrgeCn', max_length=10, null=True)),
            ],
            options={
                'db_table': 'parking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Safe112',
            fields=[
                ('safe112id', models.CharField(db_column='safe112Id', max_length=30, primary_key=True, serialize=False)),
                ('safe112mlsfcname', models.CharField(db_column='safe112MlsfcName', max_length=10)),
                ('safe112fcltyname', models.CharField(db_column='safe112FcltyName', max_length=30)),
                ('safe112ctprvnname', models.CharField(blank=True, db_column='safe112CtprvnName', max_length=10, null=True)),
                ('safe112signguname', models.CharField(blank=True, db_column='safe112SignguName', max_length=10, null=True)),
                ('safe112legaldongname', models.CharField(blank=True, db_column='safe112LegaldongName', max_length=10, null=True)),
                ('safe112legaldongcd', models.CharField(blank=True, db_column='safe112LegaldongCd', max_length=10, null=True)),
                ('safe112la', models.FloatField(db_column='safe112La')),
                ('safe112lo', models.FloatField(db_column='safe112Lo')),
            ],
            options={
                'db_table': 'safe112',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Safe119',
            fields=[
                ('safe119id', models.CharField(db_column='safe119Id', max_length=30, primary_key=True, serialize=False)),
                ('safe119fcltyname', models.CharField(db_column='safe119FcltyName', max_length=30)),
                ('safe119mlsfcname', models.CharField(db_column='safe119MlsfcName', max_length=10)),
                ('safe119la', models.FloatField(db_column='safe119La')),
                ('safe119lo', models.FloatField(db_column='safe119Lo')),
            ],
            options={
                'db_table': 'safe119',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('toiletid', models.CharField(db_column='toiletId', max_length=30, primary_key=True, serialize=False)),
                ('toiletfcltyname', models.CharField(db_column='toiletFcltyName', max_length=30)),
                ('toiletctprvnname', models.CharField(blank=True, db_column='toiletCtprvnName', max_length=10, null=True)),
                ('toiletsignguname', models.CharField(blank=True, db_column='toiletSignguName', max_length=10, null=True)),
                ('toiletlegaldongcd', models.CharField(blank=True, db_column='toiletLegaldongCd', max_length=10, null=True)),
                ('toiletlegaldongname', models.CharField(blank=True, db_column='toiletLegaldongName', max_length=10, null=True)),
                ('toiletaddrnew', models.CharField(blank=True, db_column='toiletAddrNew', max_length=50, null=True)),
                ('toiletaddrold', models.CharField(blank=True, db_column='toiletAddrOld', max_length=50, null=True)),
                ('toiletla', models.FloatField(db_column='toiletLa')),
                ('toiletlo', models.FloatField(db_column='toiletLo')),
                ('toiletaditdc', models.CharField(blank=True, db_column='toiletAditDc', max_length=10, null=True)),
            ],
            options={
                'db_table': 'toilet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Valley',
            fields=[
                ('valleyid', models.AutoField(db_column='valleyId', primary_key=True, serialize=False)),
                ('valleyname', models.CharField(db_column='valleyName', max_length=30)),
                ('valleyaddrnew', models.CharField(blank=True, db_column='valleyAddrNew', max_length=50, null=True)),
                ('valleytelno', models.CharField(blank=True, db_column='valleyTelNo', max_length=20, null=True)),
                ('valleyla', models.FloatField(db_column='valleyLa')),
                ('valleylo', models.FloatField(db_column='valleyLo')),
                ('valleyunitescore', models.IntegerField(db_column='valleyUniteScore')),
                ('valleyreviewscore', models.IntegerField(db_column='valleyReviewScore')),
            ],
            options={
                'db_table': 'valley',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Waterplay',
            fields=[
                ('waterplayid', models.AutoField(db_column='waterplayId', primary_key=True, serialize=False)),
                ('waterplayname', models.CharField(db_column='waterplayName', max_length=30)),
                ('waterplayimgurl', models.CharField(blank=True, db_column='waterplayImgUrl', max_length=100, null=True)),
                ('waterplayaddrold', models.CharField(blank=True, db_column='waterplayAddrOld', max_length=50, null=True)),
                ('waterplayaddrnew', models.CharField(blank=True, db_column='waterplayAddrNew', max_length=50, null=True)),
                ('waterplaytelno', models.CharField(blank=True, db_column='waterplayTelNo', max_length=20, null=True)),
                ('waterplayurl', models.CharField(blank=True, db_column='waterplayUrl', max_length=100, null=True)),
                ('waterplayla', models.FloatField(db_column='waterplayLa')),
                ('waterplaylo', models.FloatField(db_column='waterplayLo')),
                ('waterplaysubname', models.CharField(db_column='waterplaySubName', max_length=10)),
                ('waterplaysubid', models.IntegerField(db_column='waterplaySubId')),
                ('waterplayvalue01', models.CharField(blank=True, db_column='waterplayValue01', max_length=100, null=True)),
                ('waterplayname01', models.CharField(blank=True, db_column='waterplayName01', max_length=100, null=True)),
                ('waterplayvalue02', models.CharField(blank=True, db_column='waterplayValue02', max_length=100, null=True)),
                ('waterplayname02', models.CharField(blank=True, db_column='waterplayName02', max_length=100, null=True)),
                ('waterplayvalue03', models.CharField(blank=True, db_column='waterplayValue03', max_length=100, null=True)),
                ('waterplayname03', models.CharField(blank=True, db_column='waterplayName03', max_length=100, null=True)),
                ('waterplayvalue04', models.CharField(blank=True, db_column='waterplayValue04', max_length=100, null=True)),
                ('waterplayname04', models.CharField(blank=True, db_column='waterplayName04', max_length=100, null=True)),
                ('waterplayvalue05', models.CharField(blank=True, db_column='waterplayValue05', max_length=100, null=True)),
                ('waterplayname05', models.CharField(blank=True, db_column='waterplayName05', max_length=100, null=True)),
                ('waterplayvalue06', models.CharField(blank=True, db_column='waterplayValue06', max_length=100, null=True)),
                ('waterplayname06', models.CharField(blank=True, db_column='waterplayName06', max_length=100, null=True)),
                ('waterplayvalue07', models.CharField(blank=True, db_column='waterplayValue07', max_length=100, null=True)),
                ('waterplayname07', models.CharField(blank=True, db_column='waterplayName07', max_length=100, null=True)),
                ('waterplayunitescore', models.IntegerField(db_column='waterplayUniteScore')),
                ('waterplayreviewscore', models.IntegerField(db_column='waterplayReviewScore')),
            ],
            options={
                'db_table': 'waterplay',
                'managed': False,
            },
        ),
    ]
